server:
  port: 8086 #服务端口

spring:
  application:
    name: config-server #指定服务名
  cloud:
    config:
      label: master
      server:
        git: #配置git仓库地址
          searchPaths: springcloudConfig
          uri: https://github.com/lch1991/springcloud/
          #username:
          #password:
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ipAddress: 127.0.0.1
management:
  security:
    enabled: false #是否开启actuator安全认证
